brew "libevent"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "gnupg"
brew "pinentry-mac"
brew "php@8.4", link: true
brew "mycli"
brew "tmux"
brew "tree"
brew "aqua"
brew "claude-code-router"
brew "kubernetes-cli"
brew "peco"
brew "ripgrep"
brew "libyaml"
brew "mise"
brew "uv"
cask "docker-desktop"
cask "gcloud-cli"
cask "vagrant"
cask "vagrant-vmware-utility"

uv "claude-monitor"
