unbind C-b
set -g prefix C-t
set -g default-terminal "tmux-256color"

# change the pane
bind p select-pane -U
bind n select-pane -D
bind b select-pane -L
bind f select-pane -R

# change window
bind C-p previous-window
bind C-n next-window
bind C-t last-window

# locale
set -g update-environment LC_CTYPE

# history
set -g history-limit 10000

# copy & paste
bind -T copy-mode Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind C-y paste-buffer

# split pane
bind | split-window -h
bind - split-window -v

setw -g mode-key emacs
set -g base-index 1

# resize pane
bind -r Left resize-pane -L
bind -r Down resize-pane -D
bind -r Up resize-pane -U
bind -r Right resize-pane -R

# solarized color settings
# https://github.com/seebi/tmux-colors-solarized/blob/master/tmuxcolors-dark.conf
# default statusbar colors
set-option -g status-bg black #base02
set-option -g status-fg yellow #yellow

set-window-option -g window-status-current-format "#[fg=black,bg=yellow,bold] #I: #W #[default]"

# pane number display
set-option -g display-panes-active-colour blue #blue
set-option -g display-panes-colour brightred #orange

# clock
set-window-option -g clock-mode-colour green #green

# reload configuration file
bind C-r source-file ~/.tmux.conf \;\
     display "Reloaded configuration file"
