#!/bin/env zsh

local r branch
branch=$(git branch -a | peco | tr -d ' ')
if [ -n "$branch" ]; then
    if [[ "$branch" =~ "remotes/" ]]; then
        local b
        b=$(echo $branch | awk -F '/' '{print $3}')
        r="git checkout -b '${b}' ${branch}"
    else
        r="git checkout '${branch}'"
    fi
fi
_on-complete $r
