#!/bin/env zsh

local ssh_config_path=~/.ssh/config
if [ ! -f ${ssh_config_path} ]; then
    echo "Could not find ${ssh_config_path}"
    return
fi

local r
r=$(grep "Host " $ssh_config_path | grep -v '*' | grep -v '#' | cut -b 6- | peco)
if [ -n "$r" ]; then
    _on-complete "ssh $r"
fi
